import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
// import Login from './Components/Login.jsx'
// import LandingPage from './Components/LandingPage.jsx'
// import DashboardTiles from './Components/Core/DashboardTiles.jsx'
// import PublicFooter from './Components/PublicLayout/PublicFooter.jsx'
// import TeacherDashboard from './Components/Dashboard/TeacherDashboard.jsx'
// import Studentsidebar from './Components/Core/Studentsidebar.jsx'
// import Index from './Components/Courselist/Index.jsx'
// import CourseCreation from './Components/Course/CourseCreation.jsx'
// import Studentdashboard from './Components/Dashboard/Studentdashboard.jsx'
// import Updatestudentdetail from './Components/Editstudentdetail/Updatestudentdetail.jsx'
import Upcomingschedule from './Components/Studentupcomingschedule/Upcomingshedule.jsx'
import Upcomingschedule1 from './Components/Studentupcomingschedule/Upcomingschedule1.jsx'
// import Education from './Components/TeacherApplication/Education.jsx'
// import Forumdetail from './Components/Forum/Forumdetail.jsx'
// import List  from './Components/Favouritecourse/List.jsx'
// import CourseList from './Components/Courselist/Index.jsx'
// import Index from './Components/CourseCategory/Index.jsx'
import CoursesCreation from './Components/Course/CourseCreation.jsx'
import Studentdashboard from './Components/Dashboard/Studentdashboard.jsx'
import Index from './Components/CourseCategory/Index.jsx'
import Quize from './Components/ListOfQuize/Quize.jsx'
import  HomeWork  from './Components/Homework/Homework.jsx'
import Activecourses from './Components/ActiveEnroleCourses/ActiveCourses.jsx'
import CompleteCourse from './Components/CompleteCourseList/CompleteCourse.jsx'
import CourseHistory from './Components/CourseHistory/CourseHistory.jsx'
import Transcript from './Components/Studenttranscript/Transcript.jsx'
import ApplicationFormConfirmation from './Components/TeacherApplication/Applicationform.jsx'
import DisplayTeacherApplication from './Components/TeacherApplication/DisplayAplication.jsx'
// import Admindashboard from './Components/Dashboard/Admindashboard.jsx'
// import DashboardTiles from './Components/core/DashboardTiles.jsx'
import OnlineProfileDetails from './Components/TeacherApplication/OnlineProfile.jsx'
import WizardForm from './Components/TeacherApplication/WizardForm.jsx'
import TeacherApplicationForAdmin from './Components/TeacherApplicationForAdmin/Index.jsx'
import TeacherAvailable from './Components/TeacherAvailablity/Index.jsx'
import TeacherCourseList from './Components/TeacherCourseList/Index.jsx'
import TeacherPayment from './Components/TeacherPayment/TeacherPayment.jsx'
import TeacherHomeworkReview from './Components/TeacherHomeWorkReview/Index.jsx'
import TeacherList from './Components/TeacherList/Index.jsx'
// import TeacherPublicProfile from './Components/TeacherPublicProfile/Index.jsx'
import TeacherPublicProfile from './Components/TeacherPublicProfile/TeacherPublicProfile.jsx'
import TeacherQuizReview from './Components/TeacherQuizeReview/Index.jsx'
import TestListTable from './Components/TestListTable/Index.jsx'
import UpcomingTeacherScheduleList from './Components/UpcomingTeacherScheduleList/Index.jsx'
// import Studentsignup from './Components/Studentsignup.jsx'
// import Teachersignup from './Components/Teachersignup.jsx'
// import Login from './Components/Login.jsx'
createRoot(document.getElementById('root')).render(
  <StrictMode> 
    {/* <Upcomingschedule1/> */}
    <UpcomingTeacherScheduleList/>
  </StrictMode>,
)

